In [5]:
import pandas as pd
path = "shopping_trends_updated.csv"
df = pd.read_csv(path)
df

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3895,3896,40,Female,Hoodie,Clothing,28,Virginia,L,Turquoise,Summer,4.2,No,2-Day Shipping,No,No,32,Venmo,Weekly
3896,3897,52,Female,Backpack,Accessories,49,Iowa,L,White,Spring,4.5,No,Store Pickup,No,No,41,Bank Transfer,Bi-Weekly
3897,3898,46,Female,Belt,Accessories,33,New Jersey,L,Green,Spring,2.9,No,Standard,No,No,24,Venmo,Quarterly
3898,3899,44,Female,Shoes,Footwear,77,Minnesota,S,Brown,Summer,3.8,No,Express,No,No,24,Venmo,Weekly
3899,3900,52,Female,Handbag,Accessories,81,California,M,Beige,Spring,3.1,No,Store Pickup,No,No,33,Venmo,Quarterly

In [6]:
df_noid = df.iloc[:, 7:]
df_noid

,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
0,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly
1,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly
2,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly
3,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly
4,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually
...,...,...,...,...,...,...,...,...,...,...,...
3895,L,Turquoise,Summer,4.2,No,2-Day Shipping,No,No,32,Venmo,Weekly
3896,L,White,Spring,4.5,No,Store Pickup,No,No,41,Bank Transfer,Bi-Weekly
3897,L,Green,Spring,2.9,No,Standard,No,No,24,Venmo,Quarterly
3898,S,Brown,Summer,3.8,No,Express,No,No,24,Venmo,Weekly
3899,M,Beige,Spring,3.1,No,Store Pickup,No,No,33,Venmo,Quarterly

In [7]:
df['Previous Purchases'].describe()

count    3900.000000
mean       25.351538
std        14.447125
min         1.000000
25%        13.000000
50%        25.000000
75%        38.000000
max        50.000000
Name: Previous Purchases, dtype: float64

### Analisis Previous Purchases

Analisis statistik deskriptif dilakukan pada kolom **Previous Purchases**
menggunakan fungsi `describe()`.

Hasil analisis meliputi:

- Mean: nilai rata-rata jumlah pembelian sebelumnya.
- Std: standar deviasi yang menunjukkan tingkat penyebaran data dari nilai rata-rata.
- Min jumlah pembelian sebelumnya yang paling rendah.
- Q1 (25%) nilai kuartil pertama, yaitu batas 25% data terendah.
- Q2 (50%) nilai median atau nilai tengah data.
- Q3 (75%) nilai kuartil ketiga, yaitu batas 75% data.
- Max jumlah pembelian sebelumnya yang paling tinggi.

Analisis ini digunakan untuk mengetahui karakteristik dan persebaran
jumlah pembelian sebelumnya pada pelanggan.

In [8]:
previous = df['Previous Purchases']

print("Mean :", previous.mean())
print("Std  :", previous.std())
print("Min  :", previous.min())
print("Q1   :", previous.quantile(0.25))
print("Q2   :", previous.quantile(0.50))
print("Q3   :", previous.quantile(0.75))
print("Max  :", previous.max())

Mean : 25.35153846153846
Std  : 14.447125170462309
Min  : 1
Q1   : 13.0
Q2   : 25.0
Q3   : 38.0
Max  : 50

### Hasil Statistik Previous Purchases

Nilai statistik deskriptif pada kolom **Previous Purchases** digunakan
untuk mengetahui nilai rata-rata, penyebaran, nilai minimum, kuartil,
median, dan nilai maksimum dari jumlah pembelian sebelumnya.

Nilai **mean** menunjukkan rata-rata pembelian sebelumnya, sedangkan
**standard deviation (std)** menunjukkan seberapa besar variasi data
terhadap nilai rata-ratanya.

Q1, Q2, dan Q3 digunakan untuk mengetahui posisi distribusi data,
sedangkan min dan max menunjukkan rentang nilai terendah hingga tertinggi.

In [9]:
df[['Age', 'Purchase Amount (USD)']].corr()

                            Age  Purchase Amount (USD)
Age                    1.000000              -0.010424
Purchase Amount (USD) -0.010424               1.000000

### Korelasi Age vs Purchase Amount (USD)

Analisis korelasi dilakukan untuk mengetahui hubungan antara **Age**
dan **Purchase Amount (USD)**.

Fungsi `corr()` digunakan untuk menghitung koefisien korelasi antara
kedua variabel.

Nilai korelasi berada pada rentang **-1 hingga 1**:

- Nilai mendekati **1** menunjukkan hubungan positif yang kuat.
- Nilai mendekati **-1** menunjukkan hubungan negatif yang kuat.
- Nilai mendekati **0** menunjukkan hubungan yang sangat lemah atau hampir tidak ada.

Berdasarkan nilai korelasi yang diperoleh dari dataset, hubungan antara
usia pelanggan dan jumlah pembelian dapat dianalisis berdasarkan
arah dan kekuatan nilai korelasinya.

In [10]:
df[['Purchase Amount (USD)', 'Review Rating']].corr()

                       Purchase Amount (USD)  Review Rating
Purchase Amount (USD)               1.000000       0.030776
Review Rating                       0.030776       1.000000

### Korelasi Purchase Amount (USD) vs Review Rating

Analisis korelasi selanjutnya dilakukan untuk mengetahui hubungan antara
**Purchase Amount (USD)** dan **Review Rating**.

Fungsi `corr()` digunakan untuk menghitung koefisien korelasi antara
jumlah pembelian dan rating yang diberikan pelanggan.

Nilai korelasi positif menunjukkan bahwa kedua variabel cenderung
bergerak searah, sedangkan nilai korelasi negatif menunjukkan bahwa
kedua variabel cenderung bergerak berlawanan arah.

Semakin mendekati nilai 0, hubungan antara kedua variabel semakin lemah.